### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by ssoonmi** [lhsteele/Organa#2]
### `users`
- [x] a `user` can have many teams, so it's better to have a join table between `users` and `teams` than having a `team_id` column on the `users` table which forces `users` to belong_to `teams`

### `projects`
- [x] a `project` should belong to the person who created the `project`, not the team. The owner should be able to add teams onto a project if desired, so you should have a join table between a `project` and a `team` instead of having the `team_id` on `projects`
- [x] need `owner_id` column

### `lists`
- [x] not sure if you are planning to implement `lists` in a `project` or not

### `teams`
- [x] a `team` should not belong_to a `project`, so there is no need for the `project_id`
- [x] a `team` should not belong_to a `member` either, so there is no need for the `member_id`. Instead, you should have a join table between `teams` and `members` because a `team` can have many `members` and a `user` can have many `teams`

**Comment by lhsteele** [comment]
re: lists, I was planning on creating a <ul> out of the tasks assigned to that project, and since tasks have a project_id, I wasn't going to add lists to the project schema. Would you recommend a different approach?

**Comment by ssoonmi** [comment]
I would recommend projects > lists > tasks.
so tasks belongs to lists, and lists belongs to projects

**Comment by lhsteele** [comment]
My approach was to keep the scope as small as possible, and expand if I am able to. So I was hoping to have just the one view (list) to start with, and then add in a separate board view if I was able to .. so I guess that's why I wasn't thinking of it like that. But it makes sense that even if I do take that approach, later when I do want to add in board I need to have the db set up correctly in order to allow that. 

I've updated the schema so that tasks have a list_id foreign key, and lists have a project_id foreign key. I didn't create another joins table because it's a one directional relationship, not a many to many.  Would that be right?

**Comment by ssoonmi** [comment]
Yep that looks good!

**Comment by lhsteele** [comment]
I added image_url to the users table, because even though I don't think it will be a part of my initial project scope, once I get to implementing uploading a profile picture I figured the db should be set up to hold that. But I haven't added it to the Sample State, since I don't think I'll need to keep it in the store.
